[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastmri"
version = "0.1.0"
description = "Local copy of fastMRI"
authors = [{ name = "Mikhail Aptukov" }]
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["fastmri*"]
